# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  database: sample_app_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: sample_app_production
  pool: 5
  timeout: 5000
  username: root
  password:
  encoding: utf8
  host: localhost
  socket: /tmp/mysql.sock

